
- name: Create .ssh directory in user's home
  file:
    path="~{{ outbound.user }}/.ssh"
    state=directory
    owner="{{ outbound.user }}"
  sudo: yes

- name: Copy ssh private key
  copy:
    src="{{ outbound.private_key.file }}"
    dest="~{{ outbound.user }}/.ssh/{{ outbound.private_key.name }}"
    mode=0600
    owner="{{ outbound.user }}"
  sudo: yes

- name: Set ssh configuration for git (host)
  lineinfile:
    dest="~{{ outbound.user }}/.ssh/config"
    create=yes
    line="Host {{ item }}"
  with_items: outbound.hosts

- name: Set ssh configuration for git (key path)
  lineinfile:
    dest="~{{ outbound.user }}/.ssh/config"
    insertafter="Host {{ item }}"
    line=" IdentityFile ~/.ssh/{{ outbound.private_key.name }}"
  with_items: outbound.hosts
